# Generated by Django 4.0.4 on 2022-05-27 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False, verbose_name='ID autoincrementable del genero')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero del creepy')),
            ],
        ),
        migrations.CreateModel(
            name='mensajesadmi2',
            fields=[
                ('idmensaje', models.AutoField(primary_key=True, serialize=False, verbose_name='id del mensaje')),
                ('mensaje', models.TextField(verbose_name='Nmensaje del admi')),
                ('consultasadmi', models.CharField(max_length=20, verbose_name='tipo consulta')),
            ],
        ),
        migrations.CreateModel(
            name='creepypasta',
            fields=[
                ('idcreepypasta', models.AutoField(primary_key=True, serialize=False, verbose_name='id del creepypasta')),
                ('resumen', models.TextField()),
                ('nombrecreepy', models.CharField(max_length=20, verbose_name='Nombre del creepypasta')),
                ('historia', models.TextField(verbose_name='')),
                ('imagen', models.ImageField(upload_to='creepypastas')),
                ('generos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.genero')),
            ],
        ),
    ]
