# Generated by Django 4.0.4 on 2022-05-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreepyPasta',
            fields=[
                ('idcreepypasta', models.AutoField(primary_key=True, serialize=False, verbose_name='id del creepypasta')),
                ('resumen', models.TextField()),
                ('nombrecreepy', models.CharField(max_length=20, verbose_name='Nombre del creepypasta')),
                ('historia', models.TextField(verbose_name='')),
                ('imagen', models.ImageField(upload_to='creepypastas')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False, verbose_name='ID autoincrementable del genero')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero del creepy')),
            ],
        ),
        migrations.CreateModel(
            name='MensajesAdmi2',
            fields=[
                ('idmensaje', models.AutoField(primary_key=True, serialize=False, verbose_name='id del mensaje')),
                ('mensaje', models.TextField(verbose_name='Nmensaje del admi')),
                ('consultasadmi', models.CharField(max_length=20, verbose_name='tipo consulta')),
            ],
        ),
    ]
