# Generated by Django 4.0.4 on 2022-05-30 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paginas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creepypasta',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paginas_historia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creepypasta',
            name='generos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.genero'),
        ),
        migrations.AddField(
            model_name='creepypasta',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='creepy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='paginas.creepypasta'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
