# Generated by Django 4.0.4 on 2022-05-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creepypasta',
            name='historia',
            field=models.TextField(verbose_name='Historia'),
        ),
    ]
